# TensorFlow Fundamentals

In this notebook, we are going to cover some of the most fundamental concepts of tensors using Tensorflow.

We are going to cover: 
- Introduction to tensors
- Getting information from tensors
- Manipulating tensors 
- Tensors & Numpy
- Using @tf.function (a way to speed up your regular Python functions)
- Using GPUs with TensorFlow (or TPUs)
- Exercises to try for yourself

## Introduction to Tensor

In [1]:
# Import TensorFlow alias tf 
import tensorflow as tf
# Check the version
print(tf.__version__)

2.7.0


### Creating Tensors with `tf.constant()`

There are few different ways to create tensors. In general, we won't create many tensors ourselves. This is because TensorFlow has many different built-in modules.

For now we are going to get familiar with tensors themselves.

In [2]:
# Create tensors with tf.constat()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

See the docs - [tf.constant()](https://www.tensorflow.org/api_docs/python/tf/constant?hl=ru)

In [3]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# Create a vector, passing Python List
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimension of our vector
vector.ndim

1

In [6]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
# Number of dimensions of the matrix
matrix.ndim

2

In [8]:
# Create another matrix 
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8.,9.]], dtype=tf.float16) # specify the data type with dtype parameter 
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
# What is the number the dimensions of another_matrix ? 
another_matrix.ndim

2

In [10]:
# Let's create a tensor 
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,16,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 16, 18]]], dtype=int32)>

In [11]:
# What is the number of dimensions of the tensor ? 
tensor.ndim

3

### Summary

What we've created so far: 
- Scalar: a single number
- Vector: a number with direction (e.g. wind speed and direction)
- Matrix: a 2-dimensional array of numbers
- Tensor: an n-dimensional array of numbers (where n can be any number, a 0 dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

### Creating Tensors with `tf.Variable`

See the docs - [tf.Variable](https://www.tensorflow.org/api_docs/python/tf/Variable)

In [12]:
# Type of the tf.Variable
tf.Variable

tensorflow.python.ops.variables.Variable

- The `tf.Variable()` constructor requires an initial value for the variable, which can be a Tensor of any type and shape.

- This initial value defines the type and shape of the variable. 
 
- After construction, the type and shape of the variable are fixed.
 
- The **value can be changed** using one of the assign methods.

In [13]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

Let's try change one of the elements in our changeable tensor. 

In [14]:
# This should fail
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

How about we try .assign() ?

In [15]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

Let's try change our unchangeable tensor

In [16]:
# This should fail also
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

### Summary

- Tensor, which is created with `tf.Variable`,  is **changeable** using `assign()` method. 
- Tensor, which is created with `tf.constant`,  is **unchangeable**.
- Why can we change some tensors and why we can't change some tensors ? 
  - When we are writing new Neural Network, we might want some tensors values **to be changed** (`tf.Variable`) and we might want some tensors values **not to be changed** (`tf.constant`). 

🔑 **Note**: Rarely in practice will you need to decide whether to use `tf.constant` or `tf.variable` to create tensors, as TensorFlow does this for you. However, if in doubt, use `tf.constant` and change it later if needed. 

### Creating Random Tensors with TensorFlow

Random tensors are tensors of some arbitrary size which contain random numbers.

In [17]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

[tf.random.uniform()](https://www.tensorflow.org/api_docs/python/tf/random/uniform?hl=ru)

[Uniform distribution](https://www.investopedia.com/terms/u/uniform-distribution.asp)

In [18]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

[tf.random.normal()](https://www.tensorflow.org/api_docs/python/tf/random/normal)

[Normal Distribution](https://www.investopedia.com/terms/n/normaldistribution.asp)

In [19]:
# Are they equal ?? 
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

Why it is happening ? Why are they equal ? 

Those random tensors are actually preudo-random numbers. They appear as random, but they are really aren't. That's because we have set the seed using `from_seed()` method.

### Shuffle the orders of elements in a tensor

[tf.random.shuffle()](https://www.tensorflow.org/api_docs/python/tf/random/shuffle)

In [20]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't affect learning)
not_shuffled = tf.constant([[10, 7],
                            [3,4],
                            [2,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [21]:
not_shuffled.ndim

2

In [22]:
# Shuffle our non-shuffled tensor 
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [23]:
# Shuffle our non-shuffled tensor with seed
tf.random.set_seed(42) # Global level random seed
tf.random.shuffle(not_shuffled, seed=42) # Operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

With the set seed, we are getting the same order. 

[tf.random.set_seed](https://www.tensorflow.org/api_docs/python/tf/random/set_seed)

🧰 **Exercise**: Read through TensorFlow documenation on random seed generation (https://www.tensorflow.org/api_docs/python/tf/random/set_seed) and practice writing 5 random tensors and shuffle them. 

It looks liek if we want our shuffled tensors to be in the same order, we have got to use the global level random seed as well as operation level random seed. 

> Rule 4: If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

### Other ways to create tensors (Numpy)

[tf.ones](https://www.tensorflow.org/api_docs/python/tf/ones) - similar to NumPy.ones

In [24]:
# Create a tensor of all ones, shape = 10, 7
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

[tf.zeros](https://www.tensorflow.org/api_docs/python/tf/zeros) - similar to Numpy.zeros

In [25]:
# Create a tensor of all zeros
tf.zeros(shape=(10,7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

#### Turn NumPy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing). Otherwise, they are really similar.

In [26]:
import numpy as np 

numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25 

numpy_A
# X = tf.constant(some_matrix) # capital for matrix or tensor 
# y = tf.constant (vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [27]:
# Convert NumPy array into Tensors form
A = tf.constant(numpy_A) # This is a vector 
# Changing the shape of it
B = tf.constant(numpy_A, shape=(2,3,4)) # This is a tensor, it has got more than 1 dimension
A, B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

🔑 **Note**: Important thing to know about shape is that if we want to readjust the shape of a tensor or an array, the new elements(values) in `shape` must add up to get the same number of elements in the original array/tensor

In [28]:
2 * 3 * 4

24

In [29]:
# Check the dimensions
A.ndim

1

In [30]:
# Check the dimensions
B.ndim

3

### Getting information from tensors

How can we get more information from the tensors? 

When dealing with tensors we probably want to be aware of the following attributes: 
- Shape
- Rank
- Axis or dimension
- Size

In [31]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [32]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [33]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [34]:
2 * 3 * 4 * 5 # Size of the 4 rank tensor

120

In [35]:
# Get various attributes of out tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis", rank_4_tensor.shape[0])
print("Element along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis 2
Element along the last axis:  5
Total number of elements in our tensor:  120


In [36]:
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor))

Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)


## Indexing and expanding our tensors

Tensors can be indexed just like Python lists.

In [37]:
# Get the first 2 elements of each dimension 
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [38]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:] # single column - get all elements

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [39]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [40]:
# Get the last item of each of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [41]:
# Add in extra dimension to our rank 2 tensor 

rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [42]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [43]:
tf.expand_dims(rank_2_tensor, axis=0) # expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [44]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

## Manipulating tensors (tensor operations)

Finding patterns in data that is stored in tensor format, often involves manipulating tensors. 

When building deep learning models, much of the tensor manipulation is done for us. 

### Basic Operations
- `+` addition
- `-` subtraction
- `*` multiplication
- `\` division

**Basic operations** are often referred to as **element wise operations**.

Element wise means go through one element at a time and apply math operation (addition, subtraction, multiplication, division)

In [45]:
# We can add values to a tensor using the addtion operator
tensor = tf.constant([[10,7], [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [46]:
# Original tensor is unchanged 
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [47]:
# Multiplication also works 
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [48]:
# Subtraction 
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [49]:
# Division
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

### TensorFlow functions

We can use the tensorflow built-in functions too. If we have to do some math tensorflow operaitons and want our code to be speed up (execute faster), it is prefered to use tensorflow built-in functions. 

- [tf.math](https://www.tensorflow.org/api_docs/python/tf/math)

In [50]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [51]:
# the original tensor is still unchanged.
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

## Matrix Multiplication

In machine learning, matrix multiplication is one of the most common tensor operations. 

There are two rules our tensors (or matrices) need to fulfil if we're going to matrix multiply them:
1. The inner dimensions must match
2. The resulting has the shape of the outer dimensions

- [Matrix Multiplication - Math is fun](https://www.mathsisfun.com/algebra/matrix-multiplying.html)
- [Matrix Multiplication - visualization](http://matrixmultiplication.xyz/)

Let's see matrix multiplication in TensorFlow. This will be done by using `matmul` function - [tf.linalg.matmul](https://www.tensorflow.org/api_docs/python/tf/linalg/matmul)

In [52]:
print(tensor)
tf.matmul(tensor, tensor) # This is done by doing dot operation

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [53]:
tensor * tensor # different result since it is element wise operation

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [54]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [55]:
tensor.shape

TensorShape([2, 2])

Matrix multiplication on tensors with different shapes

In [56]:
# Create a tensor (3, 2)
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
# Create another tensor (3, 2)
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [57]:
# Try to matrix multiply tensors of same shape
X @ Y # Error the inner dimensions must match

InvalidArgumentError: ignored

Let's fix this by changing the shape of Y

In [58]:
# Change the shape of Y
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [59]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [60]:
X.shape, tf.reshape(Y, shape=(2, 3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [61]:
# Lets try to multiply X by reshaped Y
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [62]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

Let's reshape X this time

In [63]:
tf.matmul(tf.reshape(X,shape=(2,3)), Y) # The result is different - shape (2, 3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [64]:
tf.reshape(X, shape=(2,3)).shape, Y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

🔑 **Note**:  When we are dealing with matrix multiplications using dot product, it really depends on which tensor we manipulate. 

### Tensor transformation - transpose

We can do the same with transpose. However, it is slightly different to what the reshape is. 

In [65]:
X, tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

Let's try matrix multiplication with transpose rather than reshape

In [66]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

## The dot product

Matrix multiplication is also referred to as the dot product.

We can perform matrix multiplication using: 
- `tf.matmul()` - [tf.linalg.matmul](https://www.tensorflow.org/api_docs/python/tf/linalg/matmul)
- `tf.tensordot()` - [tf.tensordot](https://www.tensorflow.org/api_docs/python/tf/tensordot)

In [67]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [68]:
# Perform the dor product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [69]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [70]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [71]:
# Check the values of Y, reshape ^ and transposed Y
print("Normal Y")
print(Y, "\n") # \n is for newline 

print("Y reshaped to (2,3)")
print(tf.reshape(Y, shape=(2,3)), "\n")

print("Y transposed")
print(tf.transpose(Y), "\n")

Normal Y
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3)
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32) 



In [72]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

🔑 **Note**: Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to satisfy the matrix multiplication rules.  

## Changing the datatype of a tensor

In [73]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [74]:
C = tf.constant([7, 10])
C, C.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>,
 tf.int32)

In [75]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [76]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [77]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

## Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values. 

In [78]:
# Create a tensor 
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [79]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregations:
- Get the minimum
- Get the maximum
- Get the mean of a tensor
- Get the sum of a tensor

In [80]:
# Create a random tensor with values between and 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([21, 38, 30, 61, 58, 52,  5, 22, 38,  1, 68, 29, 32, 93, 48, 88,  1,
       61, 71, 83,  0, 56, 27, 73, 31, 60, 14, 86,  9, 66, 51, 54, 58, 53,
       73, 93, 24, 89, 13,  0, 59, 38, 97, 51,  8, 28, 27, 96, 21, 11])>

In [81]:
tf.size(E), E.shape, E.ndim, E.dtype

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1, tf.int64)

In [82]:
# Find the minimum 
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [83]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [84]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=45>

In [85]:
# Find the sum 
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2266>

In [86]:
# Find the variance
tf.math.reduce_variance(E) # Error: Input must be either real or complex

TypeError: ignored

To fix this issue, we need to cast the dtype to floating point. Let's change it to `float32`. See https://stackoverflow.com/questions/67934042/cannot-run-tf-math-reduce-std-and-tf-math-reduce-variance-in-tensorflow-error

In [91]:
# Change from int32 to float32
E_float32 = tf.cast(E, dtype=tf.float32)
E_float32

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([21., 38., 30., 61., 58., 52.,  5., 22., 38.,  1., 68., 29., 32.,
       93., 48., 88.,  1., 61., 71., 83.,  0., 56., 27., 73., 31., 60.,
       14., 86.,  9., 66., 51., 54., 58., 53., 73., 93., 24., 89., 13.,
        0., 59., 38., 97., 51.,  8., 28., 27., 96., 21., 11.],
      dtype=float32)>

In [92]:
# Find the variance
tf.math.reduce_variance(E_float32) 

<tf.Tensor: shape=(), dtype=float32, numpy=821.5776>

In [93]:
# Find the std (Standard Deviation)
tf.math.reduce_std(E_float32)

<tf.Tensor: shape=(), dtype=float32, numpy=28.663174>

## Find the position minimum and maximuma

In [94]:
# Create a new tensor for finding positional minumum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [95]:
# Find the positional maximum - often referred as argmax - Numpy alternative - np.argmax()
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [96]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [97]:
# Find the maximum value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [98]:
# Check for equality 
assert F[tf.argmax(F)] == tf.reduce_max(F)

In [99]:
# Find the positional minimum - often referred as argmin - Numpy alternative - np.argmin()
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [100]:
# Find the minimum using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

## Squeezing a tensor (removing all single dimensions)

In [101]:
# Create a tensor to  get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [102]:
G.shape

TensorShape([1, 1, 1, 1, 50])

`tf.squeeze()` - removes dimensions of size 1 from the shape of a tensor.

https://www.tensorflow.org/api_docs/python/tf/squeeze

In [103]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

## One-hot Encoding tensors 

In [104]:
# Create a list of indices 
some_list = [0,1,2,3] # could be red, green, blue, purple

# One hot encode our list of indices 
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [105]:
# Specify custom values for one hot encoding 
tf.one_hot(some_list, depth=4, on_value="I like Deep Learning", off_value="I also like Machine Learning.")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I like Deep Learning', b'I also like Machine Learning.',
        b'I also like Machine Learning.',
        b'I also like Machine Learning.'],
       [b'I also like Machine Learning.', b'I like Deep Learning',
        b'I also like Machine Learning.',
        b'I also like Machine Learning.'],
       [b'I also like Machine Learning.',
        b'I also like Machine Learning.', b'I like Deep Learning',
        b'I also like Machine Learning.'],
       [b'I also like Machine Learning.',
        b'I also like Machine Learning.',
        b'I also like Machine Learning.', b'I like Deep Learning']],
      dtype=object)>

## More math operations 

- Squaring 
- Log
- Square Root

In [106]:
# Create a new tensor 
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [107]:
# Square it 
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [108]:
# Find the square root - https://www.tensorflow.org/api_docs/python/tf/math/sqrt
tf.sqrt(tf.cast(H, dtype=tf.float32)) # Method requires non-int dtype

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [109]:
# Find the log - https://www.tensorflow.org/api_docs/python/tf/math/log
tf.math.log(tf.cast(H, dtype=tf.float32)) # Method requires non-int dtype

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and NumPy

TensorFlow interacts beautifully with NumPy arrays

In [110]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([3., 7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [111]:
# Convert our tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [112]:
# Convert tensor J to a Numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [113]:
J = tf.constant([3.])
# Accessing an element - Numpy
J.numpy()[0]

3.0

In [114]:
# The default types of each are slightly different 
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3.,7.,10.])
# Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

## Finding access to GPUs 

In [115]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [116]:
!nvidia-smi

Mon Feb 14 01:58:56 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P0    27W /  70W |    266MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

If we have access to a CUDA-enabled GPU, TensorFlow will automatically use it whenever possible. 